web:
    image: mkenney/base-web:latest
    container_name: mkenney-base-web
    ports:
        - "80"
    hostname: mkenney-base-web
    volumes:
        - .:/var/www/html/
        - /tmp/docker/var/log/httpd:/var/log/httpd
        - /etc/localtime:/etc/localtime:ro
    environment:
        - server_env=dev
        - env=1
        - is_docker=1
        - VIRTUAL_HOST=docker.9c0.com # Used in the vhost config and can also be
                                      # used by the mkenney/reverse-proxy reverse
                                      # proxy docker container
