web:
    image: mkenney/base-web:latest
    ports:
        - "80:80"
    hostname: docker.9c0.com
    volumes:
        - .:/var/www/html/
        - /tmp:/tmp
        - /tmp/common-web-logs/log/httpd:/var/log/httpd
        - /etc/localtime:/etc/localtime:ro
    environment:
        - server_env=dev
        - env=1
        - is_docker=1
        - HTTPD_CONF_SERVERNAME=docker.9c0.com
