web:
    #image: mkenney/base-web:latest
    image: mkenney/base-web:v0.2.0
    container_name: mkenney-base-web
    ports:
        - "80"
    hostname: mkenney-base-web
    volumes:
        - .:/var/www/html/
        - /tmp/docker/var/log/httpd:/var/log/httpd
        - /etc/localtime:/etc/localtime:ro
    environment:
        - server_env=dev
        - is_docker=1
        - DOCUMENTROOT_PATH=/var/www/html/documentroot # Configurable, defaults to
                                                       # /var/www/html/documentroot
        - VIRTUAL_HOST=base-web.dev.9c0.com # Used in the vhost config and can also be
                                        # used by the mkenney/reverse-proxy reverse
                                        # proxy docker container
